"""customer auth fields

Revision ID: c385a65dd399
Revises: 9d50b3bba5fe
Create Date: 2026-07-30 01:45:48.990722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c385a65dd399'
down_revision: Union[str, None] = '9d50b3bba5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('house', sa.String(length=50), nullable=True),
    sa.Column('apartment', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('receiver_name', sa.String(length=255), nullable=True),
    sa.Column('receiver_phone', sa.String(length=20), nullable=True),
    sa.Column('is_default_shipping', sa.Boolean(), nullable=True),
    sa.Column('is_default_billing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.add_column('customers', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('avatar', sa.String(length=500), nullable=True))
    op.add_column('customers', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('newsletter', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('customers', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('phone_verified', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('email_verification_code', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('phone_verification_code', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('email_verification_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('phone_verification_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('password_reset_code', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'is_blocked')
    op.drop_column('customers', 'locked_until')
    op.drop_column('customers', 'failed_login_attempts')
    op.drop_column('customers', 'last_login')
    op.drop_column('customers', 'password_reset_expires')
    op.drop_column('customers', 'password_reset_code')
    op.drop_column('customers', 'phone_verification_expires')
    op.drop_column('customers', 'email_verification_expires')
    op.drop_column('customers', 'phone_verification_code')
    op.drop_column('customers', 'email_verification_code')
    op.drop_column('customers', 'phone_verified')
    op.drop_column('customers', 'email_verified')
    op.drop_column('customers', 'password_hash')
    op.drop_column('customers', 'timezone')
    op.drop_column('customers', 'language')
    op.drop_column('customers', 'newsletter')
    op.drop_column('customers', 'gender')
    op.drop_column('customers', 'avatar')
    op.drop_column('customers', 'email')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
